url: "https://devleoko.github.io/JustADownloadPage/"
title: "A Short Hike - German"
description: "A Short Hike - German translation files"
reportUrl: "https://github.com/DevLeoko/JustADownloadPage/issues"
donateUrl: "https://www.paypal.com/"
downloads:
  - name: "ver 1.68 - a-short-hike mountainquest.yarn"
    date: "July 28, 2020"
    url: "https://fuly.network/tp/testfile.zip"
  - name: "ver 1.67 - a-short-hike mountainquest.yarn"
    date: "July 4, 2020"
    url: "https://fuly.network/tp/testfile.zip"
  - name: "ver 1.66 - a-short-hike mountainquest.yarn"
    date: "June 28, 2020"
    url: "https://fuly.network/tp/testfile.zip"
  - name: "ver 1.65 - a-short-hike mountainquest.yarn"
    date: "June 28, 2020"
    url: "https://fuly.network/tp/testfile.zip"
  - name: "ver 1.64 - a-short-hike mountainquest.yarn"
    date: "June 3, 2020"
    url: "https://fuly.network/tp/testfile.zip"
  - name: "ver 1.63 - a-short-hike mountainquest.yarn"
    date: "May 25, 2020"
    url: "https://fuly.network/tp/testfile.zip"