url: "https://devleoko.github.io/JustADownloadPage/"
title: "A Short Hike - German Translation - Fox network"
description: "A Short Hike - German translation files"
reportUrl: "https://t1317894.typeform.com/to/BYYsXOBm"
impressumUrl: "https://fuly.network/impressum"
donateUrl: "./donate"
youtubeVideoId: "l4bWwobx_LQ"
downloads:
  - name: "ver 1.8 - a-short-hike german translation - build 1"
    date: "September 11, 2020"
    url: "https://fuly.network/ash-ger-files/v18/ash_ger_v18_b001.zip"
  - name: "ver 1.4 - a-short-hike german translation - build 1"
    date: "September 11, 2020"
    url: "https://fuly.network/ash-ger-files/v14/ash_ger_v14_b001.zip"
